name: run-tests
on: [push]
jobs:
  run-tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: python -m pip install pytest
      - run: python -m pip install click
      - run: make tests
