name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: "3.5"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names.
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Limit line length according to PEP8 guidelines.
          flake8 . --count --max-complexity=10 --max-line-length=80 --statistics
      - name: Run tests
        run: python -m pytest
